services:
  - type: worker
    name: makuna-discord-onbot
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python onbot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: STATE_FILE
        value: /tmp/onbot_state.json   # ephemeral
